version: '3.8'

services:
  upornot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server-list.yaml:/app/server-list.yaml
      - ./static:/app/static
    restart: unless-stopped
    environment:
      - TZ=UTC